kindergartenNetwork/Controllers/ManagementController.cs
 using System;
using System.Collections.Generic;
 using System.Data.Entity;
 using System.Data.SqlClient;
 using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
 using System.Web.UI.WebControls;
 using EntityFrameworkPaginate;
 using kindergartenNetwork.Helper;
using kindergartenNetwork.Models.DataTableModels;
using Newtonsoft.Json;
using kindergartenNetwork.Models;
 using kindergartenNetwork.Controllers;
 using kindergartenNetwork.Models.MainModels;
 using Microsoft.Ajax.Utilities;


 namespace kindergartenNetwork.Controllers
{
    public class ManagementController : BaseController
    {
        private static kindergartenNetworkEntities _db = new kindergartenNetworkEntities();
        // GET: Management
        //public ActionResult Index()
        //{
        //    return View();
        //}
        #region Constant
        public ActionResult Constant()
        {
            var oModel = new ConstantModel();
            var getParentConstant = _db.Constants.Where(x=>x.ParentId == 0 && x.IsDeleted == false ).ToList();
            if (getParentConstant.Count > 0)
            {
                oModel.LstConstants = getParentConstant;
            }
            return View(oModel);
        }
        public JsonResult GetConstantDataTable(JQueryDataTableParamModel param)
        {
            #region byDefaultReturnData

            int rowCount = 0;
            int lnRowCount = 0;
            var result = from q in new List<Constant>()
                         select new
                         {
                             q.Id,
                             ConstantName = q.NameAr,
                             ParentName = q.Parent.NameAr,
                             q.ParentId,
                             q.Comment,
                             q.Icon
                         };

            #endregion
            var oConstant = new Constant();


            if (!string.IsNullOrEmpty(Request.QueryString["ConstantId"]))
                oConstant.Id = Convert.ToInt32(Request.QueryString["ConstantId"]);
            if (!string.IsNullOrEmpty(Request.QueryString["ParentId"]))
                oConstant.ParentId = Convert.ToInt32(Request.QueryString["ParentId"]);

            DataTableProcessModel m = new DataTableProcessModel();
            DataTableProcessModel dtProcess = DataTableProcesses.DataTableEslestir(param, m);
            //oConstant.SortCol = dtProcess.SortCol;
            //oConstant.SortType = dtProcess.SortType;
            //oConstant.Page = dtProcess.Page;
            //oConstant.RowPerPage = dtProcess.RowPerPage;
            var filters = new Filters<Constant>();
            filters.Add(oConstant.Id > 0, x => x.Id == oConstant.Id);
            filters.Add(oConstant.ParentId > 0, x => x.ParentId == oConstant.ParentId);
            filters.Add(true, x => x.IsDeleted == false);

            var sorts = new Sorts<Constant>();
            sorts.Add(dtProcess.SortCol == "Id", x => x.Id);
            sorts.Add(dtProcess.SortCol == "NameAr", x => x.NameAr);
            sorts.Add(dtProcess.SortCol == "parentId", x => x.ParentId);

            var getConstant = _db.Constants.Paginate(dtProcess.Page, dtProcess.RowPerPage, sorts, filters);

            if (getConstant.RecordCount >0)
            {
                var getConstantResult = getConstant.Results.ToList();
                foreach (var constant in getConstantResult)
                {
                    constant.Parent = getConstantResult.FirstOrDefault(x => x.Id == constant.ParentId);
                }
                rowCount = getConstant.RecordCount;
                lnRowCount = rowCount;

                result = from q in getConstantResult
                         select new
                         {
                             q.Id,
                             ConstantName = q.NameAr,
                             ParentName = q.Parent?.NameAr,
                             q.ParentId,
                             q.Comment,
                             q.Icon
                         };

            }
            return Json(new
            {
                param.sEcho,
                iTotalRecords = rowCount,
                iTotalDisplayRecords = lnRowCount,
                aaData = result
            },
                JsonRequestBehavior.AllowGet);
        }
        public PartialViewResult InsertConstantModal()
        {
            var oModel = new ConstantModel();
            var getParentConstant = _db.Constants.Where(x=>x.ParentId == 0 && x.IsDeleted == false ).ToList();
            if (getParentConstant.Count > 0)
            {
                oModel.LstConstants = getParentConstant;
            }
            return PartialView("ConstantParts/_ConstantInsertModal", oModel);
        }
        public PartialViewResult UpdateConstantModal(string id)
        {
            var constantId = Convert.ToInt32(id);
            var oModel = new UpdateConstantModel();
            var getParentConstant = _db.Constants.Where(x=>x.ParentId == 0 && x.IsDeleted == false).ToList();
            if (getParentConstant.Count > 0)
            {
                oModel.LstConstants = getParentConstant;
            }
            if (constantId > 0)
            {
                var getConstant = _db.Constants.Where(x=> x.Id == constantId ).ToList();
                if (getConstant.Count > 0)
                    oModel.OConstant = getConstant.FirstOrDefault();
            }
            return PartialView("ConstantParts/_ConstantUpdateModal", oModel);
        }
        public JsonResult InsertConstant([Bind(Exclude = "Id")] Constant oConstant)
        {
            var cStatus = "error";
            var cMsg = Resources.NotifyMsg.ErrorMsg;
            if (ModelState.IsValid)
            {
                var oUserTypeInsert = _db.Constants.Add(oConstant);
                if (oUserTypeInsert.Id > 0)
                {
                    cStatus = "success";
                    cMsg = Resources.NotifyMsg.InsertSuccessMsg;
                    return Json(new { cStatus, cMsg }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(new { cStatus = "notValid", cMsg = Resources.NotifyMsg.NotValidMsg }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { cStatus, cMsg }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UpdateConstant(Constant oConstant)
        {
            var cStatus = "error";
            var cMsg = Resources.NotifyMsg.ErrorMsg;
            if (ModelState.IsValid)
            {
                var constant = _db.Constants.FirstOrDefault(x => x.Id == oConstant.Id);
                if (constant != null) {

                    _db.Constants.Attach(constant);
                    constant.NameAr = oConstant.NameAr;
                    constant.NameEn = oConstant.NameEn;
                    constant.Icon = oConstant.Icon;
                    constant.ParentId = oConstant.ParentId;
                    constant.Comment = oConstant.Comment;
                    _db.Entry(constant).Property(x => x.NameAr).IsModified = true;
                    _db.Entry(constant).Property(x => x.NameEn).IsModified = true;
                    _db.Entry(constant).Property(x => x.Icon).IsModified = true;
                    _db.Entry(constant).Property(x => x.ParentId).IsModified = true;
                    _db.Entry(constant).Property(x => x.Comment).IsModified = true;

                    _db.SaveChanges();
                    cStatus = "success";
                    cMsg = Resources.NotifyMsg.UpdateSuccessMsg;
                }
                return Json(new { cStatus, cMsg }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                cStatus = "notValid";
                cMsg = Resources.NotifyMsg.NotValidMsg;
            }
            return Json(new { cStatus, cMsg }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteConstant(int id)
        {
            var cStatus = "error";
            var cMsg = Resources.NotifyMsg.ErrorMsg;
            var oConstant = new Constant();
            oConstant.Id = Convert.ToInt32(id);

            var constant = _db.Constants.First(x => x.Id == oConstant.Id);
            if (constant != null)
            {
                _db.Constants.Attach(constant);
                constant.IsDeleted = true;
                _db.Entry(constant).Property(x => x.IsDeleted).IsModified = true; 
                _db.SaveChanges();
                cStatus = "success";
                cMsg = Resources.NotifyMsg.DeleteSuccessMsg;
            }

            return Json(new {cStatus, cMsg}, JsonRequestBehavior.AllowGet);

        }
        public JsonResult ConstantSearchAutoComplete(string id)
        {
            var getConstantResult = new List<Constant>();
            var getConstant =
                _db.Constants.Where(x => x.NameAr.Contains(id.Trim())).ToList();

            if (getConstant.Count > 0)
            {
                getConstantResult = getConstant;
                var result = from q in getConstantResult
                             select new
                             {
                                 Name = q.NameAr,
                                 q.Id
                             };
                return Json(result, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(getConstantResult, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region Users
        public ActionResult Users()
        {
            var oModel = new UserModel();

            var getLstType = _db.UserTypes.Where(x=>x.IsDeleted == false).ToList();
            if (getLstType.Count > 0)
            {
                oModel.LstUserTypes = User.UserTypeId == 1 ? getLstType : getLstType.Where(x => x.Id != 1).ToList();
            }

kindergartenNetwork/Views/Management/UserParts/_ChangePasswordModel.cshtml
@model kindergartenNetwork.Models.MainModels.ProfileModel
	<div class="modal-dialog">
		<div class="modal-content">
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
		        <h4 class="modal-title">@kindergartenNetwork.Resources.PublicNews.ChangePassword</h4>
		    </div>
         @using (Html.BeginForm("UpdatePassword", "Management", FormMethod.Post, new {@onsubmit = "return false;", @class = "form-horizontal form-row-seperated", @id = "UpdatePassForm",@name="UpdatePassForm"}))
         {
              <div class="modal-body">
              <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button> @kindergartenNetwork.Resources.PublicNews.ErrorInField.
                </div>
                <div class="alert alert-success display-hide">
                    <button class="close" data-close="alert"></button>
                </div>
                <div class="form-horizontal">

                    <div class="form-group">
                        <label class="col-md-4 control-label">@kindergartenNetwork.Resources.PublicNews.CurrentPass</label>
                        <div class="col-md-8">
                            <div class="formElement">
                                <input type="password" id="tbCurrentPassword" name="CurrentPassword" class="form-control input-inline input-medium" placeholder="@kindergartenNetwork.Resources.PublicNews.CurrentPass" data-field="@kindergartenNetwork.Resources.PublicNews.CurrentPass" />
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-4 control-label">@kindergartenNetwork.Resources.PublicNews.NewPassword</label>
                        <div class="col-md-8">
                            <div class="formElement">
                                <input type="password" id="tbNewPassword" name="NewPassword" class="form-control input-inline input-medium" placeholder="@kindergartenNetwork.Resources.PublicNews.NewPassword" data-field="@kindergartenNetwork.Resources.PublicNews.NewPassword"/>
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>
                 <div class="form-group">
                        <label class="col-md-4 control-label">@kindergartenNetwork.Resources.PublicNews.ConfirmPassword</label>
                        <div class="col-md-8">
                            <div class="formElement">
                                <input type="password" id="tbConfirmPassword" name="ConfirmPassword" class="form-control input-inline input-medium" placeholder="@kindergartenNetwork.Resources.PublicNews.ConfirmPassword" data-field="@kindergartenNetwork.Resources.PublicNews.ConfirmPassword"/>
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
             <div class="modal-footer">
                 <button type="button" class="btn dark btn-outline" data-dismiss="modal">@kindergartenNetwork.Resources.PublicNews.Close</button>
                <button type="submit" class="btn green btn-outline">@kindergartenNetwork.Resources.PublicNews.Save</button>
                 <button type="reset" class="btn red btn-outline">@kindergartenNetwork.Resources.PublicNews.Reset</button>

             </div>
         }
		</div>
			       
	</div>
			    

kindergartenNetwork/Views/Management/UserParts/_UserAddEditType.cshtml
@model kindergartenNetwork.Models.MainModels.UserTypeModel
	<div class="modal-dialog">
		<div class="modal-content">
		    <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
		        <h4 class="modal-title">@kindergartenNetwork.Resources.PublicNews.Add/@kindergartenNetwork.Resources.PublicNews.Edit</h4>
		    </div>
         @using (Html.BeginForm("AddEditUserType", "Management", FormMethod.Post, new {@onsubmit = "return false;", @class = "form-horizontal form-row-seperated", @id = "AddUserType",@name="AddUserType"}))
         {
             <div class="modal-body">
                <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button> @kindergartenNetwork.Resources.PublicNews.ErrorInField.
                </div>
                 <div class="alert alert-success display-hide">
                     <button class="close" data-close="alert"></button>
                 </div>
                 @Html.AntiForgeryToken()
                <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.Name</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <input type="text" id="tbName" name="Name" class="form-control input-inline input-medium" placeholder="@kindergartenNetwork.Resources.PublicNews.Name" data-field="@kindergartenNetwork.Resources.PublicNews.Name" value="@Model.OUserType.Name" />
                                <span class="help-inline"></span>
                                <input type="hidden" id="tbID" name="ID" value="@Model.OUserType.Id" />
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>

             </div>
             <div class="modal-footer">
                 <button type="button" class="btn dark btn-outline" data-dismiss="modal">@kindergartenNetwork.Resources.PublicNews.Close</button>
                <button type="submit" class="btn green btn-outline">@kindergartenNetwork.Resources.PublicNews.Save</button>
                 <button type="reset" class="btn red btn-outline">@kindergartenNetwork.Resources.PublicNews.Reset</button>

             </div>
         }
		</div>
			       
	</div>
			    

kindergartenNetwork/Views/Management/UserParts/_UserInsertModal.cshtml
@model kindergartenNetwork.Models.MainModels.UserModel
@using (Html.BeginForm("InsertUser", "Management", FormMethod.Post, new {@onsubmit = "return false;", @id = "InsertUserForm",name="InsertUserForm"}))
{
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title">@kindergartenNetwork.Resources.PublicNews.Edit @kindergartenNetwork.Resources.PublicNews.User </h4>
            </div>

            <div class="modal-body">
                <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button> @kindergartenNetwork.Resources.PublicNews.ErrorInField.
                </div>
                <div class="alert alert-success display-hide">
                    <button class="close" data-close="alert"></button>
                </div>
                <div class="form-horizontal">
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.Name</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <input type="text" id="tbName" name="Name" class="form-control input-inline input-medium" placeholder="@kindergartenNetwork.Resources.PublicNews.Name" data-field="@kindergartenNetwork.Resources.PublicNews.Name"/>
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.Pass</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <input type="password" id="tbPass" name="Pass" class="form-control input-inline input-medium" placeholder="@kindergartenNetwork.Resources.PublicNews.Pass" data-field="@kindergartenNetwork.Resources.PublicNews.Pass"/>
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.ConfirmPassword</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <input type="password" id="tbConfirmPassword" name="ConfirmPassword" class="form-control input-inline input-medium" placeholder="@kindergartenNetwork.Resources.PublicNews.ConfirmPassword" data-field="@kindergartenNetwork.Resources.PublicNews.ConfirmPassword"/>
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.Email</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <input type="Email" id="tbEmail" name="Email" class="form-control input-inline input-medium" placeholder="@kindergartenNetwork.Resources.PublicNews.Email" data-field="@kindergartenNetwork.Resources.PublicNews.Email"/>
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>

                    @*                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.kindergartenNetwork.EmailPassword</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <input type="password" id="tbEPass" name="EmailPassword" class="form-control input-inline input-medium" placeholder="@kindergartenNetwork.Resources.kindergartenNetwork.EmailPassword" data-field="@kindergartenNetwork.Resources.kindergartenNetwork.EmailPassword"/>
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>*@
                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.Gender</label>
                        <div class="col-md-9">
                            <div class="radio-list">
                                <div class="formElement">
                                    <label class="radio-inline ">
                                        <input type="radio" id="tbMale" name="Gender" value="M" data-field="@kindergartenNetwork.Resources.PublicNews.Male"/>@kindergartenNetwork.Resources.PublicNews.Male
                                        <span class="help-inline"></span>
                                    </label>

                                    <label class="radio-inline ">
                                        <input type="radio" id="tbFemale" name="Gender" value="F" data-field="@kindergartenNetwork.Resources.PublicNews.Female"/>@kindergartenNetwork.Resources.PublicNews.Female
                                        <span class="help-inline"></span>
                                    </label>

                                </div>

                            </div>

                        </div>
                    </div>


                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.Mobile</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <input type="text" id="tbMobile" required name="Mobile" class="form-control input-inline input-medium" placeholder="@kindergartenNetwork.Resources.PublicNews.Mobile" data-field="@kindergartenNetwork.Resources.PublicNews.Mobile"/>
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.UserType</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <select class="form-control input-md input-medium selectpicker" name="UserTypeId" data-field="@kindergartenNetwork.Resources.PublicNews.UserType">
                                    <option value="">@kindergartenNetwork.Resources.PublicNews.Select</option>
                                    @foreach (var userType in Model.LstUserTypes)
                                    {
                                        <option value="@userType.Id">@userType.Name</option>
                                    }

                                </select>
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.ManagerGroupId</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <select class="form-control input-md input-medium selectpicker" name="ManagerGroupId" data-field="@kindergartenNetwork.Resources.PublicNews.ManagerGroupId">
                                    <option value="">@kindergartenNetwork.Resources.PublicNews.Select</option>
                                    @foreach (var userType in Model.LstUserTypes)
                                    {
                                        <option value="@userType.Id">@userType.Name</option>
                                    }

                                </select>
                                <span class="help-inline"></span>
                            </div>
                        </div>
                    </div>
                    

                    <div class="form-group">
                        <label class="col-md-3 control-label"></label>
                        <div class="col-md-9">
                            <div class="mt-checkbox-inline">
                                <div class="formElement">
                                    <label class="mt-checkbox">
                                        <input type="checkbox" id="cbIsActive" name="IsActive" value="true" data-field="@kindergartenNetwork.Resources.PublicNews.IsActive"> @kindergartenNetwork.Resources.PublicNews.IsActive
                                        <span></span>
                                    </label>
                                </div>
                                <div class="formElement">
                                    <label class="mt-checkbox">
                                        <input type="checkbox" id="cbTraceUserActivity" name="TraceUserActivity" value="true" data-field="@kindergartenNetwork.Resources.PublicNews.TraceUserActivity"> @kindergartenNetwork.Resources.PublicNews.TraceUserActivity
                                        <span></span>
                                    </label>
                                </div>

                            </div>
                        </div>
                    </div>
                    <input type="hidden" id="hdImage" name="Avatar" value=""/>
                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.Avatar</label>
                        <div class="col-md-9">
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;"></div>
                                <div>
                                    <span class="btn btn-default btn-file">
                                        <span class="fileinput-new">@kindergartenNetwork.Resources.PublicNews.SelectImage</span>
                                        <span class="fileinput-exists">@kindergartenNetwork.Resources.PublicNews.Change</span>
                                        <input id="imgUploadUser" type="file" name="...">
                                    </span>
                                    <a href="#" class="btn btn-default fileinput-exists uploderRemoveImg" data-dismiss="fileinput">@kindergartenNetwork.Resources.PublicNews.Remove</a>
                                </div>
                            </div>

                        </div>
                    </div>


                </div>
            </div>
             <div class="modal-footer">
                 <button type="button" class="btn dark btn-outline" data-dismiss="modal">@kindergartenNetwork.Resources.PublicNews.Close</button>
                 <button type="submit" class="btn green btn-outline">@kindergartenNetwork.Resources.PublicNews.Save</button>
                 <button type="reset" class="btn red btn-outline">@kindergartenNetwork.Resources.PublicNews.Reset</button>
             </div>
            
        </div>
    </div>
}