kindergartenNetwork/Controllers/ControlPanelController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using EntityFrameworkPaginate;
using kindergartenNetwork.Helper;
using kindergartenNetwork.Models;
using kindergartenNetwork.Models.DataTableModels;

namespace kindergartenNetwork.Controllers
{
    public class ControlPanelController : BaseController
    {
        private static kindergartenNetworkEntities _db = new kindergartenNetworkEntities();
        // GET: ControlPanel
        public ActionResult Index()
        {
            return View();
        }


        #region UploadSaveAlbumImg
        public JsonResult UploadSaveAlbumImg()
        {
            var fileName = "";
            var file = Request.Files[0];
            var albumId = Request.Form["albumId"];
            if (file != null && file.ContentLength > 0)
            {
                fileName = Path.GetFileName(file.FileName);
                if (fileName != null)
                {
                    string ext = fileName.Split('.')[fileName.Split('.').Length - 1];
                    string n = Guid.NewGuid().ToString();
                    fileName = n + "." + ext;
                    var path = Path.Combine(Server.MapPath("/Content/UploadedFile/Albums/Original/"), fileName);
                    file.SaveAs(path);
                    var thumbPath = Path.Combine(Server.MapPath("/Content/UploadedFile/Albums/Thumbnail/"), fileName);
                    var largePath = Path.Combine(Server.MapPath("/Content/UploadedFile/Albums/Large/"), fileName);
                    GeneralHelper.ResizeImage(path, thumbPath, 250, ext, true);
                    GeneralHelper.ResizeImage(path, largePath, 950, ext, false);
                }
            }


            _db.Media.Add(new Medium { MediaAlbumId = Convert.ToInt32(albumId), FilePath = fileName, MediaType = 11 });
            return Json(new { result = "success", Filename = fileName, }, JsonRequestBehavior.AllowGet);

        }
        public JsonResult UploadMemberClubImg()
        {
            var fileName = "";
            var file = Request.Files[0];
            if (file != null && file.ContentLength > 0)
            {
                fileName = Path.GetFileName(file.FileName);
                if (fileName != null)
                {
                    string ext = fileName.Split('.')[fileName.Split('.').Length - 1];
                    string n = Guid.NewGuid().ToString();
                    fileName = n + "." + ext;
                    var path = Path.Combine(Server.MapPath("/Content/UploadedFile/MemberClubFiles/Original/"), fileName);
                    file.SaveAs(path);
                    var thumbPath = Path.Combine(Server.MapPath("/Content/UploadedFile/MemberClubFiles/Thumbnail/"), fileName);
                    var largePath = Path.Combine(Server.MapPath("/Content/UploadedFile/MemberClubFiles/Large/"), fileName);
                    GeneralHelper.ResizeImage(path, thumbPath, 250, ext, true);
                    GeneralHelper.ResizeImage(path, largePath, 950, ext, false);
                }
            }
            return Json(new { result = "success", Filename = fileName, }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UpLoadMemberClubFile()
        {
            var fileName = "";
            var file = Request.Files[0];
            if (file != null && file.ContentLength > 0)
            {
                fileName = Path.GetFileName(file.FileName);
                if (fileName != null)
                {
                    string ext = fileName.Split('.')[fileName.Split('.').Length - 1];
                    string n = Guid.NewGuid().ToString();
                    fileName = n + "." + ext;
                    var path = Path.Combine(Server.MapPath("/Content/UploadedFile/MemberClubFiles/Files/"), fileName);
                    file.SaveAs(path);
                }

            }
            return Json(new { result = "success", Filename = fileName, }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UploadNewsImg()
        {
            var fileName = "";
            var file = Request.Files[0];
            if (file != null && file.ContentLength > 0)
            {
                fileName = Path.GetFileName(file.FileName);
                if (fileName != null)
                {
                    string ext = fileName.Split('.')[fileName.Split('.').Length - 1];
                    string n = Guid.NewGuid().ToString();
                    fileName = n + "." + ext;
                    var path = Path.Combine(Server.MapPath("/Content/UploadedFile/News/Original/"), fileName);
                    file.SaveAs(path);
                    var thumbPath = Path.Combine(Server.MapPath("/Content/UploadedFile/News/Thumbnail/"), fileName);
                    var largePath = Path.Combine(Server.MapPath("/Content/UploadedFile/News/Large/"), fileName);
                    GeneralHelper.ResizeImage(path, thumbPath, 250, ext, true);
                    GeneralHelper.ResizeImage(path, largePath, 950, ext, false);
                }
            }
            return Json(new { result = "success", Filename = fileName, }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UploadAlbumImg()
        {
            var fileName = "";
            var file = Request.Files[0];
            if (file != null && file.ContentLength > 0)
            {
                fileName = Path.GetFileName(file.FileName);
                if (fileName != null)
                {
                    string ext = fileName.Split('.')[fileName.Split('.').Length - 1];
                    string n = Guid.NewGuid().ToString();
                    fileName = n + "." + ext;
                    var path = Path.Combine(Server.MapPath("/Content/UploadedFile/Albums/Original/"), fileName);
                    file.SaveAs(path);
                    var thumbPath = Path.Combine(Server.MapPath("/Content/UploadedFile/Albums/Thumbnail/"), fileName);
                    var largePath = Path.Combine(Server.MapPath("/Content/UploadedFile/Albums/Large/"), fileName);
                    GeneralHelper.ResizeImage(path, thumbPath, 250, ext, true);
                    GeneralHelper.ResizeImage(path, largePath, 950, ext, false);
                }
            }
            return Json(new { result = "success", Filename = fileName, }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult UpLoadFile()
        {
            var fileName = "";
            var file = Request.Files[0];
            if (file != null && file.ContentLength > 0)
            {
                fileName = Path.GetFileName(file.FileName);
                if (fileName != null)
                {
                    string ext = fileName.Split('.')[fileName.Split('.').Length - 1];
                    string n = Guid.NewGuid().ToString();
                    fileName = n + "." + ext;
                    var path = Path.Combine(Server.MapPath("/Content/UploadedFile/Attachments/"), fileName);
                    file.SaveAs(path);
                }

            }
            return Json(new { result = "success", Filename = fileName, }, JsonRequestBehavior.AllowGet);
        }
        public static string GetMimeTypeByWindowsRegistry(string fileNameOrExtension)
        {
            string mimeType = "application/unknown";
            string ext = fileNameOrExtension.Contains(".") ? Path.GetExtension(fileNameOrExtension).ToLower() : "." + fileNameOrExtension;
            Microsoft.Win32.RegistryKey regKey = Microsoft.Win32.Registry.ClassesRoot.OpenSubKey(ext);
            if (regKey != null && regKey.GetValue("Content Type") != null) mimeType = regKey.GetValue("Content Type").ToString();
            return mimeType;
        }
        #endregion

        #region StaticPages
        public ActionResult HomePage()
        {
            var oModel = new Models.NewsModels.StaticPageModel();
            var getStaticPage = _db.StaticPages.First(x=>x.Id == 1 );
            if (getStaticPage != null)
                oModel.OStaticPage = getStaticPage;
            return View(oModel);
        }
        public ActionResult AboutPage()
        {
            var oModel = new Models.NewsModels.StaticPageModel();
            var getStaticPage = _db.StaticPages.First(x=>x.Id == 2 );
            if (getStaticPage != null)
                oModel.OStaticPage = getStaticPage;
            return View(oModel);
        }
        public ActionResult ContactPage()
        {
            var oModel = new Models.NewsModels.StaticPageModel();
            var getStaticPage = _db.StaticPages.First(x=>x.Id == 3 );
            if (getStaticPage != null)
                oModel.OStaticPage = getStaticPage;
            return View(oModel);
        }
        public JsonResult GetStaticPagesDataTable(JQueryDataTableParamModel param)
        {
            var oStaticPage = new StaticPage();
            if (!string.IsNullOrEmpty(Request.QueryString["Id"]))
                oStaticPage.Id = Convert.ToInt32(Request.QueryString["Id"]);

            DataTableProcessModel m = new DataTableProcessModel();
            DataTableProcessModel dtProcess = DataTableProcesses.DataTableEslestir(param, m);
            //oStaticPage.SortCol = dtProcess.SortCol;
            //oStaticPage.SortType = dtProcess.SortType;
            //oStaticPage.Page = dtProcess.Page;
            //oStaticPage.RowPerPage = dtProcess.RowPerPage;

            //var getStaticPage = DAL.News.StaticPages.StaticPagesGet(oStaticPage);

            //var filters = new Filters<StaticPage>();
            //filters.Add(Convert.ToBoolean(oUserType.Name), x => x.Name == oUserType.Name);
            //filters.Add(true, x => x.IsDeleted == false);

            var sorts = new Sorts<StaticPage>();
            sorts.Add(dtProcess.SortCol == "Id", x => x.Id);

kindergartenNetwork/Views/ControlPanel/CategoryParts/_CategorySaveModal.cshtml
@model kindergartenNetwork.Models.NewsModels.CategoryModel
@using (Html.BeginForm("SaveCategory", "ControlPanel", FormMethod.Post, new { @onsubmit = "return false;", @id = "SaveCategoryForm", name = "SaveCategoryForm" }))
{
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                @if (Model.OCategory.Id > 0)
                {
                <h4 class="modal-title"> @kindergartenNetwork.Resources.PublicNews.Edit @kindergartenNetwork.Resources.PublicNews.NewsCategory </h4>
                    <input type="hidden" value="@Model.OCategory.Id" Name="Id" data-field="" />

                }
                else
                {
                    <h4 class="modal-title"> @kindergartenNetwork.Resources.PublicNews.Add @kindergartenNetwork.Resources.PublicNews.NewsCategory </h4>

                }
            </div>
            <div class="modal-body">
                <div class="alert alert-danger display-hide">
                    <button class="close" data-close="alert"></button> @kindergartenNetwork.Resources.PublicNews.ErrorInField.
                </div>
                <div class="alert alert-success display-hide">
                    <button class="close" data-close="alert"></button>
                </div>
                <div class="form-horizontal ">
                    @Html.AntiForgeryToken()
                    <div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.Name</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <input type="text" id="tbNameAr" value="@Model.OCategory.NameAr" name="NameAr" class="form-control" placeholder="@kindergartenNetwork.Resources.PublicNews.Name" data-field="@kindergartenNetwork.Resources.PublicNews.Name" />
                            </div>
                        </div>
                    </div>
                    @*<div class="form-group">
                        <label class="col-md-3 control-label">@kindergartenNetwork.Resources.PublicNews.NameEn</label>
                        <div class="col-md-9">
                            <div class="formElement">
                                <input type="text" id="tbNameEn" value="@Model.OCategory.NameEn" name="NameEn" class="form-control" placeholder="@kindergartenNetwork.Resources.PublicNews.NameEn" data-field="@kindergartenNetwork.Resources.PublicNews.NameEn" />
                            </div>
                        </div>
                    </div>*@
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn dark btn-outline" data-dismiss="modal">@kindergartenNetwork.Resources.PublicNews.Close</button>
                <button type="submit" class="btn green btn-outline">@kindergartenNetwork.Resources.PublicNews.Save</button>
                <button type="reset" class="btn red btn-outline">@kindergartenNetwork.Resources.PublicNews.Reset</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
}