kindergartenNetwork/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace kindergartenNetwork.Controllers
{
    public class ArticlesController : Controller
    {
        // GET: Articles
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Details()
        {
            return View();
        }
    }
}

kindergartenNetwork/Views/Articles/Details.cshtml
@{
    ViewBag.Title = "تفاصيل المقالة | " + kindergartenNetwork.Resources.PublicNews.ProjectName;
    Layout = "~/Views/Shared/_DefLayout.cshtml";
}

<!-- Start Page Title Area -->
<div class="page-title-area bg-14">
    <div class="container">
        <div class="page-title-content">
            <h2>تفاصيل المقالة</h2>
            <ul>
                <li>
                    <a href="@Url.Action("Index","Home",null,Request.Url.Scheme)">
                        الرئيسية
                    </a>
                </li>

                <li class="active">تفاصيل المقالة</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Title Area -->
<!-- Start Blog Details Area -->
<div class="single-blog-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="single-blog-content">
                    <div class="blog-top-content">
                        <img src="/Content/defaultTheme/assets/img/single-blog/single-blog-img11.jpg" alt="Image">

                        <span class="research">تصنيف1</span>

                        <h3>يتم استخدام نص لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ</h3>

                        <ul class="post-details">
                            <li>
                                بواسطة <a href="#">Admin</a>
                            </li>
                            <li>
                                تم النشر في 13/07/2020
                            </li>
                            <li>
                                <a href="#">2 تعليقات</a>
                            </li>
                        </ul>

                        <p>
                            يوجد العديد من المواقع تقدم نسخ و فقرات متعددة من نص لوريم ايبسوم و بشكل منظم و بنظام الفقرات
                            المرتبة و المنظمة و التى تناسب القارئ و التعبير الجيد عن تنسيق الكلمات و ترتيبها و إليك بعض
                            المواقع الإلكترونية التى تقدم ذلك لوضعه في تصميم موقع الويب بلغات متعددة
                        </p>

                        <p>
                            يوجد العديد من المواقع تقدم نسخ و فقرات متعددة من نص لوريم ايبسوم و بشكل منظم و بنظام الفقرات
                            المرتبة و المنظمة و التى تناسب القارئ و التعبير الجيد عن تنسيق الكلمات و ترتيبها و إليك بعض
                            المواقع الإلكترونية التى تقدم ذلك لوضعه في تصميم موقع الويب بلغات متعددة
                        </p>

                        <p>
                            يوجد العديد من المواقع تقدم نسخ و فقرات متعددة من نص لوريم ايبسوم و بشكل منظم و بنظام الفقرات
                            المرتبة و المنظمة و التى تناسب القارئ و التعبير الجيد عن تنسيق الكلمات و ترتيبها و إليك بعض
                            المواقع الإلكترونية التى تقدم ذلك لوضعه في تصميم موقع الويب بلغات متعددة
                        </p>

                        <p>
                            يوجد العديد من المواقع تقدم نسخ و فقرات متعددة من نص لوريم ايبسوم و بشكل منظم و بنظام الفقرات
                            المرتبة و المنظمة و التى تناسب القارئ و التعبير الجيد عن تنسيق الكلمات و ترتيبها و إليك بعض
                            المواقع الإلكترونية التى تقدم ذلك لوضعه في تصميم موقع الويب بلغات متعددة
                        </p>

                        <p>
                            يوجد العديد من المواقع تقدم نسخ و فقرات متعددة من نص لوريم ايبسوم و بشكل منظم و بنظام الفقرات
                            المرتبة و المنظمة و التى تناسب القارئ و التعبير الجيد عن تنسيق الكلمات و ترتيبها و إليك بعض
                            المواقع الإلكترونية التى تقدم ذلك لوضعه في تصميم موقع الويب بلغات متعددة
                        </p>
                    </div>

                    <ul class="social-wrap">
                        <li>
                            <span>يمكنك مشاركة المقال</span>
                        </li>
                        <li>
                            <a href="#" target="_blank">
                                <i class="bx bxl-twitter"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" target="_blank">
                                <i class="bx bxl-instagram"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" target="_blank">
                                <i class="bx bxl-facebook"></i>
                            </a>
                        </li>
                        <li>
                            <a href="#" target="_blank">
                                <i class="bx bxl-youtube"></i>
                            </a>
                        </li>
                    </ul>

                    <div class="comments-wrap">
                        <h3>تعليقات (2)</h3>

                        <ul>
                            <li>
                                <img src="/Content/defaultTheme/assets/img/single-blog/comments-img-1.jpg" alt="Image">
                                <h3>تست تست</h3>
                                <span>Monday, July 20, 2020</span>

                                <p>
                                    يتم استخدام نص لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ للأحرف الموجودة في اللغة
                                    العربية بدلا من أو عوضاً عن استخدام “هنا يوجد محتوى نصي، هنا يوجد محتوى نصي” و
                                    تكرارها كثيرا في بعض المواقع الالكترونية الحديثة فيستخدم نص لوريم ايبسوم فتجعلها
                                    تبدو (أي الأحرف) وكأنها نص مقروء.
                                </p>

                                <a href="#">
                                    رد
                                </a>
                            </li>

                            <li>
                                <img src="/Content/defaultTheme/assets/img/single-blog/comments-img-2.jpg" alt="Image">
                                <h3>تست تست</h3>
                                <span>Monday, July 20, 2020</span>

                                <p>
                                    يتم استخدام نص لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ للأحرف الموجودة في اللغة
                                    العربية بدلا من أو عوضاً عن استخدام “هنا يوجد محتوى نصي، هنا يوجد محتوى نصي” و
                                    تكرارها كثيرا في بعض المواقع الالكترونية الحديثة فيستخدم نص لوريم ايبسوم فتجعلها
                                    تبدو (أي الأحرف) وكأنها نص مقروء.
                                </p>

                                <a href="#">
                                    رد
                                </a>
                            </li>
                        </ul>
                    </div>
                    <hr>
                    <div class="leave-reply-wrap">
                        <h3>إترك تعليق</h3>
                        <p>لن يتم نشر عنوان بريدك الإلكتروني. الحقول المطلوبة محددة*</p>

                        <form>
                            <div class="row">
                                <div class="col-lg-6 col-sm-6">
                                    <div class="form-group">
                                        <label>الإسم*</label>
                                        <input type="text" name="name" id="name" class="form-control">
                                    </div>
                                </div>

                                <div class="col-lg-6 col-sm-6">
                                    <div class="form-group">
                                        <label>عنوان البريد الإلكتروني*</label>
                                        <input type="email" name="email" id="email" class="form-control">
                                    </div>
                                </div>

                                <div class="col-lg-12 col-md-12">
                                    <div class="form-group">
                                        <label>التعليق</label>
                                        <textarea name="message" class="form-control" id="message" rows="8"></textarea>
                                    </div>
                                </div>

                                <div class="col-12">
                                    <div class="form-group">
                                        <input type="checkbox" id="chb2">
                                        <span>
                                            احفظ اسمي ، بريدي الإلكتروني في هذا المتصفح لاستخدامها المرة المقبلة في تعليقي.
                                        </span>
                                    </div>
                                </div>

                                <div class="col-lg-12 col-md-12">
                                    <button type="submit" class="default-btn page-btn">
                                        إرسال التعليق
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Blog Details Area -->

kindergartenNetwork/Views/Articles/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_DefLayout.cshtml";
}

<!-- Start Page Title Area -->
<div class="page-title-area bg-15">
    <div class="container">
        <div class="page-title-content">
            <h2>المقالات</h2>
            <ul>
                <li>
                    <a href="@Url.Action("Index","Home",null,Request.Url.Scheme)">
                        الرئيسية
                    </a>
                </li>

                <li class="active">المقالات</li>
            </ul>
        </div>
    </div>
</div>
<!-- End Page Title Area -->
<!-- Start Blog Column One Area -->
<div class="blog-column-one-area ptb-100">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="blog-column-ome">
                    <div class="row">
                        <div class="col-lg-12 col-md-6">
                            <div class="single-news">
                                <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">
                                    <img src="/Content/defaultTheme/assets/img/news-img/news-img-222.jpg" alt="Image">
                                </a>

                                <div class="news-content">
                                    <span class="tag">تصنيف</span>

                                    <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">
                                        <h3>يتم استخدام نص لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ  للأحرف </h3>
                                    </a>

                                    <p>و هنالك العديد من الأنواع المتوفرة لنصوص لوريم إيبسوم، ولكن الغالبية تم تعديلها بشكل ما عبر إدخال بعض النوادر أو الكلمات العشوائية إلى النص. إن كنت تريد أن تستخدم نص لوريم إيبسوم ما، عليك أن تتحقق أولاً أن ليس هناك أي كلمات أو عبارات محرجة أو غير لائقة مخبأة في هذا النص. بينما تعمل بعض مولّدات نصوص لوريم إيبسوم علىالإنترنت على إعادة تكرار مقاطع من نص لوريم إيبسوم نفسه عدة مرات بما تتطلبه الحاجة، فأن البعض الأخر يستخدم كلمات من قاموس يحوي على أكثر من 200 كلمة لا تينية، مضاف إليها مجموعة من الجمل النموذجية</p>

                                    <ul class="lessons">
                                        <li>بواسطة: <a href="#">Admin</a></li>
                                        <li class="float">تم النشر في 13/07/2020</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-6">
                            <div class="single-news">
                                <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">
                                    <img src="/Content/defaultTheme/assets/img/news-img/news-img-9.jpg" alt="Image">
                                </a>

                                <div class="news-content">
                                    <span class="tag">تصنيف</span>

                                    <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">
                                        <h3>يتم استخدام نص لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ  للأحرف </h3>
                                    </a>

                                    <p>و هنالك العديد من الأنواع المتوفرة لنصوص لوريم إيبسوم، ولكن الغالبية تم تعديلها بشكل ما عبر إدخال بعض النوادر أو الكلمات العشوائية إلى النص. إن كنت تريد أن تستخدم نص لوريم إيبسوم ما، عليك أن تتحقق أولاً أن ليس هناك أي كلمات أو عبارات محرجة أو غير لائقة مخبأة في هذا النص. بينما تعمل بعض مولّدات نصوص لوريم إيبسوم علىالإنترنت على إعادة تكرار مقاطع من نص لوريم إيبسوم نفسه عدة مرات بما تتطلبه الحاجة، فأن البعض الأخر يستخدم كلمات من قاموس يحوي على أكثر من 200 كلمة لا تينية، مضاف إليها مجموعة من الجمل النموذجية</p>

                                    <ul class="lessons">
                                        <li>بواسطة: <a href="#">Admin</a></li>
                                        <li class="float">تم النشر في 13/07/2020</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-6">
                            <div class="single-news">
                                <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">
                                    <img src="/Content/defaultTheme/assets/img/news-img/news-img-10.jpg" alt="Image">
                                </a>

                                <div class="news-content">
                                    <span class="tag">تصنيف</span>

                                    <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">
                                        <h3>يتم استخدام نص لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ  للأحرف </h3>
                                    </a>

                                    <p>و هنالك العديد من الأنواع المتوفرة لنصوص لوريم إيبسوم، ولكن الغالبية تم تعديلها بشكل ما عبر إدخال بعض النوادر أو الكلمات العشوائية إلى النص. إن كنت تريد أن تستخدم نص لوريم إيبسوم ما، عليك أن تتحقق أولاً أن ليس هناك أي كلمات أو عبارات محرجة أو غير لائقة مخبأة في هذا النص. بينما تعمل بعض مولّدات نصوص لوريم إيبسوم علىالإنترنت على إعادة تكرار مقاطع من نص لوريم إيبسوم نفسه عدة مرات بما تتطلبه الحاجة، فأن البعض الأخر يستخدم كلمات من قاموس يحوي على أكثر من 200 كلمة لا تينية، مضاف إليها مجموعة من الجمل النموذجية</p>

                                    <ul class="lessons">
                                        <li>بواسطة: <a href="#">Admin</a></li>
                                        <li class="float">تم النشر في 13/07/2020</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-6">
                            <div class="single-news">
                                <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">
                                    <img src="/Content/defaultTheme/assets/img/news-img/news-img-11.jpg" alt="Image">
                                </a>

                                <div class="news-content">
                                    <span class="tag">تصنيف</span>

                                    <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">
                                        <h3>يتم استخدام نص لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ  للأحرف </h3>
                                    </a>

                                    <p>و هنالك العديد من الأنواع المتوفرة لنصوص لوريم إيبسوم، ولكن الغالبية تم تعديلها بشكل ما عبر إدخال بعض النوادر أو الكلمات العشوائية إلى النص. إن كنت تريد أن تستخدم نص لوريم إيبسوم ما، عليك أن تتحقق أولاً أن ليس هناك أي كلمات أو عبارات محرجة أو غير لائقة مخبأة في هذا النص. بينما تعمل بعض مولّدات نصوص لوريم إيبسوم علىالإنترنت على إعادة تكرار مقاطع من نص لوريم إيبسوم نفسه عدة مرات بما تتطلبه الحاجة، فأن البعض الأخر يستخدم كلمات من قاموس يحوي على أكثر من 200 كلمة لا تينية، مضاف إليها مجموعة من الجمل النموذجية</p>

                                    <ul class="lessons">
                                        <li>بواسطة: <a href="#">Admin</a></li>
                                        <li class="float">تم النشر في 13/07/2020</li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12">
                            <div class="pagination-area">
                                <span class="page-numbers current" aria-current="page">1</span>
                                <a href="#" class="page-numbers">2</a>
                                <a href="#" class="page-numbers">3</a>
                                <a href="#" class="page-numbers">4</a>

                                <a href="#" class="next page-numbers">
                                    <i class="bx bx-chevron-right"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="widget-sidebar">
                    <div class="sidebar-widget search">
                        <form class="search-form">
                            <input class="form-control" name="search" placeholder="Search here" type="text">
                            <button class="search-button" type="submit">
                                <i class="bx bx-search"></i>
                            </button>
                        </form>
                    </div>

                    <div class="sidebar-widget categories">
                        <h3>التصنيفات</h3>

                        <ul>
                            <li>
                                <a href="#">تصنيف1</a>
                            </li>
                            <li>
                                <a href="#">تصنيف2</a>
                            </li>
                            <li>
                                <a href="#">تصنيف3</a>
                            </li>
                            <li>
                                <a href="#">تصنيف4</a>
                            </li>
                            <li>
                                <a href="#">تصنيف5</a>
                            </li>
                            <li>
                                <a href="#">تصنيف6</a>
                            </li>
                            <li>
                                <a href="#">تصنيف7</a>
                            </li>
                            <li>
                                <a href="#">تصنيف8</a>
                            </li>
                        </ul>
                    </div>

                    <div class="sidebar-widget popular-post">
                        <h3 class="widget-title">مقالات أخرى</h3>

                        <div class="post-wrap">
                            <div class="item">
                                <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)" class="thumb">
                                    <span class="fullimage cover bg1" role="img"></span>
                                </a>

                                <div class="info">
                                    <h4 class="title">
                                        <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">يتم استخدام نص لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ</a>

                                        <span class="date">20-07-2020</span>
                                    </h4>
                                </div>
                            </div>

                            <div class="item">
                                <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)" class="thumb">
                                    <span class="fullimage cover bg2" role="img"></span>
                                </a>

                                <div class="info">
                                    <h4 class="title">
                                        <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">يتم استخدام نص لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ</a>

                                        <span class="date">19-07-2020</span>
                                    </h4>
                                </div>
                            </div>

                            <div class="item">
                                <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)" class="thumb">
                                    <span class="fullimage cover bg3" role="img"></span>
                                </a>

                                <div class="info">
                                    <h4 class="title">
                                        <a href="@Url.Action("Details","Articles",null,Request.Url.Scheme)">يتم استخدام نص لوريم إيبسوم لأنها تعطي توزيعاَ طبيعياَ</a>

                                        <span class="date">18-07-2020</span>
                                    </h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Blog Column One Area -->